const { spawn } = require('child_process'), fs = require('fs'), os = require('os'), path = require('path'), crypto = require('crypto');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'pp-')), P = 4111, B = 'http://localhost:' + P;
const srv = spawn('node', ['server.js'], { env: { ...process.env, PORT: P, DATA_DIR: dir, ADMIN_EMAIL: 'a@x.com', ADMIN_PASSWORD: 'adminpass1', DEV_PAY: '1', WEBHOOK_SECRET: 'w', UPI_ID: 'prepun@okhdfcbank' } });
const call = async (m, p, t, b, h = {}) => { const r = await fetch(B + p, { method: m, headers: { ...(t ? { Authorization: 'Bearer ' + t } : {}), ...(b && !h['Content-Type'] ? { 'Content-Type': 'application/json' } : {}), ...h }, body: b && (h['Content-Type'] ? b : JSON.stringify(b)) }); return { s: r.status, j: await r.json().catch(() => null) }; };
let fail = 0; const ok = (n, c) => { console.log((c ? 'PASS ' : 'FAIL ') + n); if (!c) fail++; };
(async () => { await new Promise(r => setTimeout(r, 800));
  const adm = (await call('POST', '/api/login', 0, { email: 'a@x.com', password: 'adminpass1' })).j.token;
  const g = (await call('POST', '/api/register', 0, { email: 'g@x.com', password: 'gympass123', role: 'gym', gymName: 'Iron Yard', city: 'Ludhiana' })).j.token;
  const u = (await call('POST', '/api/register', 0, { email: 'u@x.com', password: 'userpass123', name: 'Arman' })).j.token;
  ok('bad login rejected', (await call('POST', '/api/login', 0, { email: 'u@x.com', password: 'nope' })).s === 401);
  ok('unapproved gym cannot make league', (await call('POST', '/api/leagues', g, { name: 'L', exercise: 'Bench', deadline: '2099-01-01' })).s === 403);
  const gyms = (await call('GET', '/api/admin/gyms', adm)).j; await call('POST', '/api/admin/gyms/' + gyms[0].id, adm, { status: 'approved' });
  ok('member cannot use admin', (await call('GET', '/api/admin/stats', u)).s === 403);
  ok('follow by code', (await call('POST', '/api/follow', u, { code: gyms[0].code })).s === 200);
  const l = (await call('POST', '/api/leagues', g, { name: 'Bench Blitz', exercise: 'Bench', deadline: '2099-01-01' })).j;
  const sub = (await call('POST', `/api/submissions?league=${l.id}&weight=100`, u, Buffer.from('fakevideo'), { 'Content-Type': 'video/mp4' })).j;
  ok('video upload', sub && sub.id);
  ok('stranger gym cannot review', (await call('POST', '/api/submissions/' + sub.id + '/review', u, { status: 'approved' })).s === 403);
  await call('POST', '/api/submissions/' + sub.id + '/review', g, { status: 'approved' });
  ok('leaderboard shows approved', (await call('GET', '/api/leaderboard?league=' + l.id)).j[0].weight === 100);
  const v = await fetch(B + '/api/videos/' + sub.id, { headers: { Authorization: 'Bearer ' + u } }); ok('owner can watch video', (await v.text()) === 'fakevideo');
  const sl = (await call('POST', '/api/slots', adm, { label: 'Banner', price: 2500, start: '2020-01-01', end: '2099-01-01' })).j;
  const ad = (await call('POST', '/api/ads', g, { slot: sl.id, text: 'Join us' })).j;
  ok('double booking blocked', (await call('POST', '/api/ads', g, { slot: sl.id, text: 'x' })).s === 409);
  await call('POST', `/api/ads/${ad.id}/decide`, adm, { approve: true });
  ok('unpaid ad not shown', (await call('GET', '/api/ads/active')).j.length === 0);
  const body = JSON.stringify({ adId: ad.id });
  ok('bad webhook signature rejected', (await call('POST', '/api/webhook/payment', 0, body, { 'Content-Type': 'text/plain', 'x-signature': 'bad' })).s === 401);
  await call('POST', '/api/webhook/payment', 0, body, { 'Content-Type': 'text/plain', 'x-signature': crypto.createHmac('sha256', 'w').update(body).digest('hex') });
  ok('paid ad shown', (await call('GET', '/api/ads/active')).j.length === 1);
  ok('revenue counted', (await call('GET', '/api/admin/stats', adm)).j.revenue === 2500);
  // UPI manual-confirm flow, on a second slot
  const sl2 = (await call('POST', '/api/slots', adm, { label: 'Banner 2', price: 1000, start: '2020-01-01', end: '2099-01-01' })).j;
  const ad2 = (await call('POST', '/api/ads', g, { slot: sl2.id, text: 'y' })).j;
  await call('POST', `/api/ads/${ad2.id}/decide`, adm, { approve: true });
  const withUpi = (await call('GET', '/api/ads', g)).j.find(a => a.id === ad2.id);
  ok('upi link present', withUpi.upi && withUpi.upi.startsWith('upi://'));
  ok('gym cannot self-confirm', (await call('POST', `/api/ads/${ad2.id}/confirm-payment`, g)).s === 403);
  ok('claim moves to payment claimed', (await call('POST', `/api/ads/${ad2.id}/claim-payment`, g)).j.st === 'payment claimed');
  ok('still not shown as active before admin confirms', !(await call('GET', '/api/ads/active')).j.some(a => a.text === 'y'));
  ok('admin confirms payment', (await call('POST', `/api/ads/${ad2.id}/confirm-payment`, adm)).j.st === 'paid');
  console.log(fail ? fail + ' FAILED' : 'ALL PASSED'); srv.kill(); process.exit(fail ? 1 : 0); })();
